# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e0bb1f70954877ee434d0dd94afdcaf1bf195e3b3887d53e1f4b0c08ef5c8a232525d7a8d3842026debc5dc0bae0aa2e47d38adaad554c97a8a8eef2b798935

test:
  secret_key_base: c988a3c0486529d73f024ab01df33567747409a4036cf7ab7b5176162fefd1908360ef048abadb47c7da53d480331f97ba98e8af2bafdfd59e66188d422c0223

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
